### ISSUE TITLE
64/32

### ISSUE THREAD

**Issue by SlimRG** [ShiftMediaProject/VSYASM#10]
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC -- For a 64 bit system
C:\Program Files\Microsoft Visual Studio 14.0\VC -- For a 32 bit system

**Comment by SlimRG** [comment]
Seriously????

**Comment by Sibras** [comment]
Yep, is there any particular issue you have?

**Comment by SlimRG** [comment]
Yes

**Comment by Sibras** [comment]
and that issue is.....
