### ISSUE TITLE
vs2017 Enterprise can not install yasm

### ISSUE THREAD

**Issue by zhouxs1023** [ShiftMediaProject/VSYASM#12]
Detected 64 bit system...
Downloading required vswhere release binary...
Error: Failed to download required vswhere binary!
   The following link could not be resolved "https://github.com/Microsoft/vswher
e/releases/download/2.8.4/vswhere.exe"
   Now trying fallback detection..."
Visual Studio 2017 installation detected...
Installing VS15 customisations into "D:\Program Files (x86)\Microsoft Visual Stu
dio\2017\Enterprise\"
Error: Failed to get correct msbuild path!
Error: Could not find valid Visual Studio installation!
Press any key to continue . . .

**Comment by Sibras** [comment]
Your problem is that vswhere failed to download. The vswhere link is still valid so try again, if not then check your firewall and make sure your running as admin as the error is on your end so theres nothing that can be done from VSYASM itself.
