### ISSUE TITLE
Doesn't work with VS 2022 pro

### ISSUE THREAD

**Issue by pps83** [ShiftMediaProject/VSYASM#14]
Project description mentions that vs2022 is supported, while it doesn't seem to be working at all.
I used `install_script.bat` with admin rights but cannot get any yasm related options for asm files.

Here's the output I had:
```
Detected 64 bit system...
Using existing vswhere binary...
Visual Studio 2022 environment detected...
Installing VS17 customisations into "C:\Program Files\Microsoft Visual Studio\2022\Professional"
Installing build customisations...
Downloading required YASM binary...
Press any key to continue . . .
```

Also, the [Installation](https://github.com/ShiftMediaProject/VSYASM?tab=readme-ov-file#installation) section mentions multiple VS versions, but **not** vs2022. Is it because it's not supported with the script?

**Comment by pps83** [comment]
Seems like it should have said:

To use YASM in a project you must enable the customization by right clicking on the project in the Solution Explorer and select **'Build Dependencies ->** 'Build Customisations..'.

**Comment by pps83** [comment]
@Sibras wouldn't it be easier to make an msvc extension that automatically installs it all? I did a quick look if there was something similar on github, but couldn't find anything to start from

**Comment by Sibras** [comment]
Writing this as an extension is not something I have the time to do. Last time I looked at that it wasnt as easy to do as one would like so its not something thats likely at this point. Ofcourse PRs are welcome
