### ISSUE TITLE
Could not find valid Visual Studio installation!

### ISSUE THREAD

**Issue by liriyao** [ShiftMediaProject/VSYASM#15]
![1726717282069](https://github.com/user-attachments/assets/c686135f-b74b-44c1-9995-9160ead51f75)
don't work on vs2022

**Comment by Sibras** [comment]
Run vswhere by itself from the terminal to check what it finds
```
./vswhere.exe -find MSBuild
```

then run the following command

```
./vswhere.exe -prerelease -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
```

If nothing is reported then your visual studio installation is probably incorrect. The most likely issue is that the C++ package has not been properly installed
