### ISSUE TITLE
Using VSWhere to identify VS installation

### ISSUE THREAD

**Issue by tomachristian** [ShiftMediaProject/VSYASM#2]
I had problems with corrupted VS installations and the `install_script` did not detect the installation folder properly. I had to install it manually.

An interesting ideea would be to use [VSWhere](https://github.com/Microsoft/vswhere) to identify the VS installations and their paths.

**Comment by Sibras** [comment]
Thanks for the suggestion, Detecting VS installs is a difficult problem and something that needs to be improved in the install script (which is only a lightweight installer). VSWhere may provide a solution. Although adding an external install dependency does complicate things. But this may be something i keep in mind for a future update.
