### ISSUE TITLE
error in install_script - yasm.exe vs yasm-1.3.0.exe

### ISSUE THREAD

**Issue by mediabuff** [ShiftMediaProject/VSYASM#5]
line 281:
copy /B /Y /V "%SCRIPTDIR%\yasm.*" "%VCTargetsPath%\" >nul 2>&1

**Comment by robcowell** [comment]
I just added some wildcards to the script that downloads and copies the EXE

`:InstallYASM
REM copy yasm executable to VC installation folder
echo Installing required YASM release binary...
del /F /Q "%VCINSTALLDIR%\yasm.exe" >nul 2>&1
copy /B /Y /V "%SCRIPTDIR%\yasm*.exe" "%VCINSTALLDIR%\yasm.exe" >nul 2>&1
if %ERRORLEVEL% neq 0 (
    echo Error: Failed to install YASM binary!
    echo    Ensure that this script is run in a shell with the necessary write privileges
    del /F /Q "%SCRIPTDIR%\yasm*.exe"  >nul 2>&1
    goto Terminate
)
del /F /Q "%SCRIPTDIR%\yasm*.exe"  >nul 2>&1
echo Finished Successfully
goto Exit`

**Comment by mediabuff** [comment]
Simple fix. Change lines 280 and 281

del /F /Q "%VCTargetsPath%\yasm.*" >nul 2>&1
copy /B /Y /V "%SCRIPTDIR%\yasm.*" "%VCTargetsPath%\" >nul 2>&1

del /F /Q "%VCTargetsPath%\yasm_%YASMVERSION%.*" >nul 2>&1
copy /B /Y /V "%SCRIPTDIR%\yasm_%YASMVERSION%.*" "%VCTargetsPath%\" >nul 2>&1
