### ISSUE TITLE
Can't find yasm.exe while attempting to build nettle

### ISSUE THREAD

**Issue by jkent** [ShiftMediaProject/VSYASM#8]
First off, thank you for this project.  I'm attempting to do a 64-bit static library build, and it fails.  I don't have a Windows install handy to do testing myself.

Here is a log of the build:
https://travis-ci.com/GrangerHub/OpenWolf-Libraries/builds/117410519#L182

Here is my .travis-ci.yml:
https://github.com/GrangerHub/OpenWolf-Libraries/blob/2b43607ecdd7a10c1a9c8d101818c87a1630c41b/.travis.yml#L91

My script that installs VSYASM:
https://github.com/GrangerHub/OpenWolf-Libraries/blob/2b43607ecdd7a10c1a9c8d101818c87a1630c41b/tools/install_yasm.sh

Here is my invocation of MSBuild.exe:
https://github.com/GrangerHub/OpenWolf-Libraries/blob/2b43607ecdd7a10c1a9c8d101818c87a1630c41b/.ci/build_nettle.sh#L103

**Comment by Sibras** [comment]
Should be fixed now with latest 0.5 release

**Comment by jkent** [comment]
Hmm, I'm still having build problems -- I'll look at this later today.  I just setup VS 2017 build tools last night, so I could repo it locally.


> C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\BuildCustomizations\yasm.targets(50,5): error MSB3721: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\"yasm.exe -Xvc -f win64 -o "C:\Users\travis\build\GrangerHub\OpenWolf-Libraries\build\windows-x86_64\gmp\SMP\obj\Release\x64\libgmp\addlsh1_n.obj" -rraw -pgas  "C:\Users\travis\build\GrangerHub\OpenWolf-Libraries\build\windows-x86_64\gmp\SMP\mpn\x86_64\addlsh1_n.s"" exited with code -1073741515. [C:\Users\travis\build\GrangerHub\OpenWolf-Libraries\build\windows-x86_64\gmp\SMP\libgmp.vcxproj]

**Comment by jkent** [comment]
Interesting, I'm having less luck on my notebook.  vswhere.exe can't find any installations.  I have MSBuild.exe in my path.  Any suggestions?

**Comment by jkent** [comment]
Okay, vswhere issue taken care of in pull request #9, script works fine when ran from an elevated CMD shell.  However, when calling it from a Git Bash shell has another issue.

```
jkent@DESKTOP-4FN4KVB MINGW64 ~/Projects/games/OpenWolf-Libraries/tools/vsyasm (vswhere-all)
$ cmd.exe /c install_script.bat
Detected 64 bit system...
Using existing vswhere binary...
find: ‘2019’: No such file or directory
find: ‘2017’: No such file or directory
Error: Failed to detect VS installations using vswhere!
   Now trying fallback detection...
Error: Could not find valid Visual Studio installation!
Press any key to continue . . .
```

Fixing this *should* resolve my build issues on Travis-CI

**Comment by jkent** [comment]
Investigating further, this might be a bug in vswhere.

**Comment by jkent** [comment]
Nope, was my invocation of cmd/vswhere from Git Bash.  cmd.exe /C 'VSYASM/vswhere.exe -products *' works fine.  Rookie mistake.  After looking into it more, it is the PATH environment from MSYS messing things up.  Especially the find command.

**Comment by jkent** [comment]
https://travis-ci.com/GrangerHub/OpenWolf-Libraries/builds/118041118#L38 -- this still has me confused though.  I've worked around it by using wget after cloning the repo.  Any idea?

Looks like the download of YASM fails too.  Ah-ha!

**Comment by jkent** [comment]
I'm giving up on Travis-CI for Windows and using AppVeyor, things are working like they should.  I might bug Travis support about this if I find some time.

**Comment by Sibras** [comment]
I have no idea how to help with this. Debugging inside travis isnt easy so its hard to know whats going on. All the scripts are tested in Appveyor as thats whats currently supported. Although if you do ever work out whats wrong with travis i would be interested to know.
